version: '3.8'
services:
  db:
    image: 'postgres:latest'
    container_name: 'database-container'
    environment:
      POSTGRES_USER: ${USER_POSTGRES}
      POSTGRES_PASSWORD: ${PASSWORD_POSTGRES}
      POSTGRES_DB: restaurant-management
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${USER_POSTGRES}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  application:
    container_name: 'restaurant-container'
    image: 'restaurant-aplication:1.0'
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/restaurant-management
      SPRING_DATASOURCE_USERNAME: ${USER_POSTGRES}
      SPRING_DATASOURCE_PASSWORD: ${PASSWORD_POSTGRES}
